name: 'tp-animtoolkit-maya'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Maya libraries for tpAnimToolkit framework.'
displayName: 'tpAnimToolkit Maya'
environment:
  PYTHONPATH:
    - '{self}'
  TPDCC_ANIMTOOLBOX_PLUGIN_PATHS:
    - '{self}/tp/animtoolkit/maya/tools/animtoolbox/plugins'
commands:
  - '{self}/tp/animtoolkit/startup/animtoolkitmaya.py'
